import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@/app/style/global.scss";

import Footer from "./components/Footer";
import Nav from "./components/Nav";
import { ApolloWrapper } from "./lib/apollo-wrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ApolloWrapper>
          <Nav />
          {children}
          <Footer />
        </ApolloWrapper>
      </body>
    </html>
  );
}
