import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@/app/style/global.scss";

import Footer from "./components/Footer";
import Nav from "./components/Nav";
import { ApolloWrapper } from "./lib/apollo-wrapper";
import { CartProvider } from "@/app/context/CartContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ApolloWrapper>
          <CartProvider>
            <Nav />
            {children}
            <Footer />
          </CartProvider>
        </ApolloWrapper>
      </body>
    </html>
  );
}
